spring:
  application:
    name: springboot_demo
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54322/ge_apm
    username: postgres
    password: root
  devtools:
    restart:
      enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true

  autoconfigure:
    exclude:

server:
  port: 9000