spring:
  application:
    name: springboot_demo
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/cpm_rcc
    username: postgres
    password: GehcDi9it@l
  devtools:
    restart:
      enabled: true
  jpa:
    properties:
      hibernate:
        #ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        #hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true

  autoconfigure:
    exclude:

server:
  port: ${random.int[8000,9000]}

mangement:
  endpoints:
    web:
      exposure:
        include: "*"