healthlink:
  broker-server:
    hostname: tcp://apm-dev.hcdigital.com.cn
    port: 1883
    username: ENC(dVJ0tIDP3KhueOGu8ob+krbLvpVwsGQB)
    password: ENC(c2bqjptt3UESDLoVelLUt4bG8Wak1axE)
  topic:
    log: /HealthLink/log
    event: /HealthLink/event

spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/ge_apm
    driver_class_name: org.postgresql.Driver
    username: ENC(ISQSpiVMgJOfrpZwqr4zEcVfWJr1H/Fb)
    password: ENC(OPfddipOQD51bAS2TLLpsw==)
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true

jasypt:
  encryptor:
    password: H1oFwuFRwiAOB0biZHVcjQ==