healthlink:
  broker-server:
    hostname: tcp://apm-dev.hcdigital.com.cn
    port: 1883
    username: ENC(PMLvf9Ks55A+PVJvdYh7/T0EquxPyZ3v)
    password: ENC(VVwbMgVdBrkzlPcwLc2yEUjMFNCR/JHh)
  topic:
    log: /HealthLink/log
    event: /HealthLink/event
    power: /HealthLink/power
    link: /HealthLink/link
    current: /HealthLink/current
  mqtt:
      consumer:
        client_id: ${random.value}

spring:
  datasource:
    url: jdbc:postgresql://apm-dev.hcdigital.com.cn:5432/ge_apm
    driver_class_name: org.postgresql.Driver
    username: ENC(t/NXk5iYwe5O+dKInXU+DoZA6FJgqKKW)
    password: ENC(fCnQdkmZY6nZR7He/1RXuE1m0Oq1+Unk)
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true

jasypt:
  encryptor:
    password: H1oFwuFRwiAOB0biZHVcjQ==