srping:
  datasource:
    url: jdbc:postgresql://localhost:54322/ge_apm
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root

jpa:
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.PostgreSQLDialect
    jdbc:
      lob:
        non_contextual_creation: true
  show-sql: true

